<a href="https://colab.research.google.com/github/PriyanshuChaubey/machine_learning/blob/main/House_Price_Prediction_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import seaborn as sns

In [ ]:
df = pd.read_csv("/content/HousePricePrediction (1).csv")

In [ ]:
df

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,NaN
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,NaN
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,NaN
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,NaN
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,NaN

In [ ]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [ ]:
# Pre-prcessing
df['MSZoning'] = df['MSZoning'].fillna(df['MSZoning'].mode()[0])
df['Exterior1st'] = df['Exterior1st'].fillna(df['Exterior1st'].mode()[0])
df['BsmtFinSF2'] = df['BsmtFinSF2'].fillna(0)
df['TotalBsmtSF'] = df['TotalBsmtSF'].fillna(0)

In [ ]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        0
BsmtFinSF2         0
TotalBsmtSF        0
SalePrice       1459
dtype: int64

In [ ]:
train_df = df[df["SalePrice"].notna()]
X = train_df.drop(["Id", "SalePrice"], axis=1)
y = train_df["SalePrice"]

categorical_cols = [
    "MSZoning",
    "LotConfig",
    "BldgType",
    "Exterior1st"
]

x = pd.get_dummies(
    X,
    columns = categorical_cols,
    drop_first=True
)

In [ ]:
# Train_test_split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
# Train
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [ ]:
#Pred
y_pred = model.predict(x_test)

In [ ]:
y_pred

array([168844.20187045, 243627.93266265, 114499.46802618, 157672.74928534,
       254809.72691561, 156499.88714209, 177912.63550292, 127514.41651571,
       133133.47244362, 149402.60951093, 130794.50236613, 123245.60221164,
        80364.27242007, 239205.09970653, 218458.40576163, 177909.93322611,
       217597.00518372, 179150.77327368, 135680.39694336, 232757.15292119,
       163631.47385302, 219363.09382648, 202562.61369718, 154850.31244007,
       223837.5082334 , 166839.82458248, 228156.71441652, 110537.3376599 ,
       215037.51335144, 205629.10183973, 115051.49676838, 231549.64641402,
       224622.45132016, 128364.14241411, 251497.64742701, 140828.28483851,
       170989.33623264, 217385.70991952, 255132.48015837,  77807.51078479,
       118583.69813312, 217906.68251222, 125596.27931999, 291090.36797416,
       141473.52251816, 105135.34718205, 128070.20017548, 130672.55127482,
       320648.92241053, 146484.93143582, 112112.92648899, 193792.29031155,
       123203.44465366, 262793.87552928, 152184.80649994, 259668.17086377,
       181304.6833272 , 171336.2722422 , 197876.30912178,  85228.38830292,
        62102.95785583, 209481.14094137, 244329.35354902, 246635.5994911 ,
       262490.50049667, 190164.32862604, 118949.82962346, 271985.62848979,
       163634.61994167, 179438.07971729,  55768.11463022, 116795.24157381,
       123359.8060035 ,  32918.70662506, 316563.12276763, 303979.82536625,
       254731.10963031, 252812.02526933, 178662.82190228, 124765.92487818,
       113971.86635948,  76003.47746727, 116472.72977534,  85083.69163448,
       160962.16743452, 156031.85576402, 244629.77728715, 303380.94219288,
       152182.74311379, 211524.97129731, 180606.88277149, 169029.53050378,
       141672.54292259, 213851.45085518, 184951.62507241, 224839.15571821,
       178383.64815418, 184052.60817062, 239803.23680813, 214657.24096754,
       183738.49640166, 219687.69688469, 249084.1529961 , 155756.38911794,
       229852.71547803, 187521.10968132, 167157.57751869, 316058.3882314 ,
       180773.42728393, 175220.85761882,  37377.15643787, 147407.82801282,
       168832.98887069, 175203.77499056, 229461.02344973, 128054.57040797,
       144137.91412448, 135644.18038855,  55954.24434851, 370477.82133182,
       144874.38720787, 152184.80649994, 213810.54111738, 165879.31978758,
       191780.83657805, 132893.88536864, 221279.01711631,  99429.71958334,
       203122.7594283 , 164130.65437762, 211856.41479442, 271349.49818761,
       210530.57872588, 116899.87033421,  40048.00868384, 273531.46176055,
       240209.55446476, 159130.37255934, 246152.55855011, 335527.19526131,
       261120.98434297, 172194.55010435, 169380.00549531, 138926.85162855,
       184463.29701661, 174112.13304804, 212753.77210788, 231060.65111256,
       232881.95440608,  90848.45241639,  81170.32480748, 145578.58728369,
       254316.36276369, 130797.62396711, 101165.0161348 , 124511.78193722,
       139706.20279046, 163336.87596236, 119228.66411959, 127234.4182453 ,
       219110.79277298, 144622.15025123, 253975.94741773, 167976.8319934 ,
       126827.3243782 , 224178.2824915 , 219718.07817402, 298373.40066616,
       342775.5002135 , 175332.63894463, 271326.96007277, 140011.28080094,
       132569.29230683, 114630.52556805, 255700.4275583 ,  85485.57094096,
       111643.09939274, 218151.07967307, 152354.83991095, 163781.49750225,
       289954.89013758,  63316.45971014, 202810.81377109, 137713.14631408,
       233629.50222134, 113815.62232425, 276864.36171361, 205615.50061079,
       207849.72882096, 112431.54596501, 117761.50463632, 122754.31382522,
       122337.63493875, 212804.74829274, 180535.77595806, 156627.99261707,
       197322.81685039, 119077.82223347, 181093.94416103, 102982.77096835,
       229911.46829121, 185882.57149012, 145318.04432501, 261441.98731729,
       221634.08487598, 184818.33096784, 229097.49219473, 146937.0017904 ,
       175790.47920631, 113913.77363315, 177110.55090925, 117617.73485487,
       115544.18486784, 181190.71199049, 204652.26308479, 249659.1838408 ,
       198151.96121999, 180487.33126038, 185373.73534491,  54922.32294896,
       130261.32514734, 205958.52095901, 186488.44942489, 111962.54871673,
       238601.75020538, 195384.77417087,  63388.89986829, 135635.14793439,
       182654.67565816,  75342.84437292,  81818.33126987, 177354.79579275,
       132115.74711595, 145050.95844261, 194214.13202943, 165715.95759872,
       215763.21147661, 222536.20585063, 215867.55450825, 122688.21341782,
       118914.06043252, 218103.29768153, 230607.44109262, 283534.9307701 ,
       170490.81314418, 162417.1839216 , 184093.12711839, 174149.8918461 ,
       157085.56796597,  82508.03092393, 219563.99893506, 160120.1013653 ,
       149576.46227872,  86071.77951986, 138860.77917277, 129572.15086016,
       150388.51995678, 130813.71965127, 192412.32934152, 237560.33728831,
       277815.91630082, 169401.78899344, 124450.96573021, 282670.05209815,
       282704.81826888, 242954.66266906, 167118.59921316, 151422.42456256,
       114896.38014624, 191426.59994002, 291006.61798117, 173234.09599875,
       242664.79141019, 128749.25326414,  20696.06739176, 150717.54985971,
       176336.19511994, 253638.1985833 , 238080.88417548, 138029.33014938,
       226521.8078475 , 145601.11496933, 215944.01130237, 139006.60075812,
       260288.8121471 , 233835.02930268, 224601.61987348, 155508.77878458,
       245890.13400661, 221469.28721382, 133419.64697906, 143198.3977924 ])

In [ ]:
# Evaluate
from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
print("MSE: ", mse)
r2 = r2_score(y_test, y_pred)
print("R2 score: ", r2)

MSE:  2918458029.5855145
R2 score:  0.6195131796544835